apiVersion: apps/v1
kind: Deployment
metadata:
  name: mascotas-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mascotas
  template:
    metadata:
      labels:
        component: mascotas
    spec:
      containers:
        - name: mascotas
          image: josefvivas/fmp-mascotas
          ports:
            - containerPort: 4000
          env:
            - name: BUCKET_ACCOUNT_TYPE
              value: "service_account"
            - name: BUCKET_PROJECT_ID
              value: "findmypet-387512"
            - name: BUCKET_KEY_ID
              value: "35609c9b18947ac61f779a3deb1a87e2c20eebd2"
            - name: BUCKET_CRED
              valueFrom:
                secretKeyRef:
                  name: fmp-bucket-cred
                  key: private_key
            - name: BUCKET_CLIENT_EMAIL
              value: "find-my-pet-api@findmypet-387512.iam.gserviceaccount.com"
            - name: BUCKET_CLIENT_ID
              value: "116540645008928283052"
            - name: BUCKET_AUTH_URI
              value: "https://accounts.google.com/o/oauth2/auth"
            - name: BUCKET_TOKEN_URI
              value: "https://oauth2.googleapis.com/token"
            - name: BUCKET_AUTH_PROVIDER
              value: "https://www.googleapis.com/oauth2/v1/certs"
            - name: BUCKET_CLIENT_CERT_URL
              value: "https://www.googleapis.com/robot/v1/metadata/x509/find-my-pet-api%40findmypet-387512.iam.gserviceaccount.com"
            - name: BUCKET_UNIVERSE_DOMAIN
              value: "googleapis.com"
            - name: TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: literal-token
                  key: TOKEN_SECRET
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: literal-token
                  key: PGHOST
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: literal-token
                  key: PGUSER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: literal-token
                  key: PGPASSWORD
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: literal-token
                  key: PGDATABASE
            - name: PGPORT
              valueFrom:
                secretKeyRef:
                  name: literal-token
                  key: PGPORT
        - name: cloud-sql-proxy
          # It is recommended to use the latest version of the Cloud SQL Auth Proxy
          # Make sure to update on a regular schedule!
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.1.0
          args:
            # If connecting from a VPC-native GKE cluster, you can use the
            # following flag to have the proxy connect over private IP
            # - "--private-ip"

            # Enable structured logging with LogEntry format:
            - "--structured-logs"
            # Replace DB_PORT with the port the proxy should listen on
            - "--port=5432"
            - "clean-carrier-390803:southamerica-west1:find-my-pet-bd"

            # [START cloud_sql_proxy_k8s_volume_mount]
            # This flag specifies where the service account key can be found
            - "--credentials-file=/secrets/service_account.json"
          securityContext:
            # The default Cloud SQL Auth Proxy image runs as the
            # "nonroot" user and group (uid: 65532) by default.
            runAsNonRoot: true
          volumeMounts:
            - name: postgres
              mountPath: /secrets/
              readOnly: true
          # [END cloud_sql_proxy_k8s_volume_mount]
          # Resource configuration depends on an application's requirements. You
          # should adjust the following values based on what your application
          # needs. For details, see https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
          resources:
            requests:
              # The proxy's memory use scales linearly with the number of active
              # connections. Fewer open connections will use less memory. Adjust
              # this value based on your application's requirements.
              memory: "1Gi"
              # The proxy's CPU use scales linearly with the amount of IO between
              # the database and the application. Adjust this value based on your
              # application's requirements.
              cpu: "200m"
      # [START cloud_sql_proxy_k8s_volume_secret]
      volumes:
        - name: postgres
          secret:
            secretName: fmp-bd-connect
      # [END cloud_sql_proxy_k8s_volume_secret]
